version: '3.9'
name: conv_image
services:
  conv:
    container_name: 'avif'
    image: zhangyiming748/convert_images:latest
    volumes:
      - '/home/zen/Pictures/raw/Raw:/data'
    deploy:
      resources:
        limits:
          memory: 8192M
          cpus: '4'
    environment:
      - root=/data

