version: '3.9'
name: conv_image
services:
  conv:
    container_name: 'conv'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/mnt/c/Users/zen/Downloads:/data'
    deploy:
      resources:
        limits:
          memory: 8192M
          cpus: '4'
    environment:
      - root=/data
      - to=vp9
      - level=Info
      - direction=ToRight
