version: '3.9'
name: conv_image
services:
  conv:
    container_name: 'images'
    image: zhangyiming748/convert_images
    volumes:
      - '/c/Users/zen/Pictures/Screenshots:/data'
    deploy:
      resources:
        limits:
          memory: 8192M
          cpus: '4'
    environment:
      - root=/data
      - level=Debug
